const pre_races = [
	{
		name: 'Human',
		stats: [
			{	name: 'strength',
				action: 'add',
				value: 1,
			},
			{	name: 'dexterity',
				action: 'add',
				value: 1,
			},
			{	name: 'constitution',
				action: 'add',
				value: 1,
			},
			{	name: 'intelligence',
				action: 'add',
				value: 1,
			},
			{	name: 'wisdom',
				action: 'add',
				value: 1,
			},
			{	name: 'charisma',
				action: 'add',
				value: 1,
			},
			{	name: 'speed',
				action: 'base',
				value: 30,
			},
			{	name: 'armorClass',
				action: 'base',
				value: 10,
			},
		],
	},
];
export default pre_races;
